// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {services} from '../models';
import {models} from '../models';

export function AddSingleAccount(arg1:string,arg2:string,arg3:string):Promise<main.ImportResult>;

export function ApplyAllPerformanceFixes():Promise<Record<string, string>>;

export function ApplyPerformanceFix(arg1:Array<string>):Promise<Record<string, string>>;

export function AutoDetectClashGroup():Promise<services.AutoDetectClashGroupResult>;

export function AutoSetupClash():Promise<main.AutoSetupClashResult>;

export function CleanupAllSafe():Promise<Array<main.CleanupResult>>;

export function CleanupStartupCache():Promise<Array<main.CleanupResult>>;

export function CleanupWindsurf(arg1:Array<string>):Promise<Array<main.CleanupResult>>;

export function DeleteAccount(arg1:string):Promise<void>;

export function DeleteAccountsByGroup(arg1:string):Promise<number>;

export function DeleteAllUsage():Promise<number>;

export function DeleteExpiredAccounts():Promise<number>;

export function DeleteFreePlanAccounts():Promise<number>;

export function ExportAccountsByGroup(arg1:string):Promise<string>;

export function ExportSettings():Promise<string>;

export function GetAccount(arg1:string):Promise<models.Account>;

export function GetAllAccounts():Promise<Array<models.Account>>;

export function GetCaptureDir():Promise<string>;

export function GetClashRotatorRunning():Promise<boolean>;

export function GetJailbreakDefaultOverride():Promise<string>;

export function GetJailbreakRuntime():Promise<main.JailbreakRuntime>;

export function GetManualPinStatus():Promise<main.ManualPinStatus>;

export function GetMitmCAPath():Promise<string>;

export function GetMitmDebugDumpEnabled():Promise<boolean>;

export function GetMitmFullCaptureEnabled():Promise<boolean>;

export function GetMitmProxyStatus():Promise<services.MitmProxyStatus>;

export function GetMitmSessionBindings():Promise<Array<services.SessionBindingInfo>>;

export function GetOpenAIRelayStatus():Promise<services.OpenAIRelayStatus>;

export function GetPerformanceTips():Promise<Array<main.PerformanceTip>>;

export function GetProtoDumpDir():Promise<string>;

export function GetRotationPoolStatus():Promise<main.RotationPoolStatus>;

export function GetSettings():Promise<models.Settings>;

export function GetStaticCacheDir():Promise<string>;

export function GetUsageRecords(arg1:number):Promise<Array<services.UsageRecord>>;

export function GetUsageSummary():Promise<services.UsageSummary>;

export function GetWindsurfDiskUsage():Promise<main.WindsurfDiskUsage>;

export function GetWindsurfProcessInfo():Promise<Array<Record<string, any>>>;

export function ImportByAPIKey(arg1:Array<main.APIKeyItem>):Promise<Array<main.ImportResult>>;

export function ImportByEmailPassword(arg1:Array<main.EmailPasswordItem>):Promise<Array<main.ImportResult>>;

export function ImportByJWT(arg1:Array<main.JWTItem>):Promise<Array<main.ImportResult>>;

export function ImportByRefreshToken(arg1:Array<main.TokenItem>):Promise<Array<main.ImportResult>>;

export function ImportSettings(arg1:string):Promise<void>;

export function ListClashGroupNodes(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function ListJailbreakPresets():Promise<Array<services.JailbreakPreset>>;

export function OpenJailbreakOverrideFile():Promise<string>;

export function RefreshAccountQuota(arg1:string):Promise<void>;

export function RefreshAllQuotas():Promise<Record<string, string>>;

export function RefreshAllTokens():Promise<Record<string, string>>;

export function ResetJailbreakStats():Promise<void>;

export function RevealJailbreakOverrideFolder():Promise<string>;

export function RotationPoolRefreshQuotasNow():Promise<void>;

export function RotationPoolSwitchNow():Promise<string>;

export function RunDiagnostics():Promise<main.DiagnoseReport>;

export function SaveJailbreakOverrideFile(arg1:string):Promise<string>;

export function SetSilentFromFlag(arg1:boolean):Promise<void>;

export function SetupMitmAll():Promise<Array<main.PrereqStepResult>>;

export function SetupMitmCA():Promise<void>;

export function SetupMitmHosts():Promise<void>;

export function StartMitmProxy():Promise<void>;

export function StartOpenAIRelay(arg1:number,arg2:string):Promise<void>;

export function StopMitmProxy():Promise<void>;

export function StopOpenAIRelay():Promise<void>;

export function SwitchAccountLocal(arg1:string):Promise<string>;

export function SwitchMitmToAccount(arg1:string):Promise<string>;

export function SwitchMitmToNext():Promise<string>;

export function TeardownMitm():Promise<void>;

export function TestClashController(arg1:string,arg2:string):Promise<services.ClashProbeResult>;

export function ToggleMitmDebugDump(arg1:boolean):Promise<void>;

export function ToggleMitmFullCapture(arg1:boolean):Promise<void>;

export function TriggerClashRotate():Promise<boolean>;

export function UnbindMitmSession(arg1:string):Promise<boolean>;

export function UninstallMitmCA():Promise<void>;

export function UninstallMitmHosts():Promise<void>;

export function UnpinManualAccount():Promise<void>;

export function UpdateSettings(arg1:models.Settings):Promise<void>;
